Feature/files
RoboNET/AdCampaign pull request #2
Opened 2020-12-16 18:29 UTC by MelnikovIG

2020-12-16 20:26 UTC, RoboNET requested changes
И ещё надо реализовать работу с кешированием файлов и возвращать 404 код если файла нет

2020-12-16 20:26 UTC, RoboNET commented on AdCampaign.DAL/Entities/Advert.cs
> +        public File PrimaryImage { get; set; }
Добавь явно поле с идентификатором файла, чтобы не вытаскивать через навигационные сущности идентификаторы. И лучше навигационные свойства помечать как virtual

2020-12-16 20:37 UTC, RoboNET approved these changes

2020-12-16 20:38 UTC, merged

2020-12-17 04:51 UTC, DenisPimenov commented on AdCampaign.DAL/Entities/Advert.cs
> +        public File PrimaryImage { get; set; }
https://docs.microsoft.com/en-us/ef/core/querying/related-data/lazy#lazy-loading-without-proxies